### ISSUE TITLE
Test combining Carbon and Dotcom components

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-contentful#11]
### User story

Test if the UI shell and UI shell left hand navigation can be combined with the Carbon for IBM.com components.

### Additional information

We will be providing some basic templates in Contentful v1 that will include the following components to support the DPO teams and PALs that will migrate off of Gatsby.

- [UI shell header](https://react.carbondesignsystem.com/?path=/story/components-ui-shell--header-base-w-navigation-actions-and-side-nav)
- UI shell left nav
- [Lead space](https://www.ibm.com/standards/carbon/web-components/react/?path=/story/components-leadspace--medium)
- [Content block](https://www.ibm.com/standards/carbon/web-components/react/?path=/story/components-cta-block--default)
- [Footer](https://www.ibm.com/standards/carbon/web-components/react/?path=/story/components-footer--default)

*Note: leadership will need to discuss what footer component we want to use because dotcom footer doesn't allow customization to links right now (I think?)*

**Example templates**
[Figma link](https://www.figma.com/file/XXIhC6kFHqvQf5jYiQ7GZx/Component-delta?node-id=544%3A108825&t=5hx39aToxdAKqkve-1)
<img width="1496" alt="Screenshot 2023-01-09 at 9 27 12 AM" src="https://user-images.githubusercontent.com/45692622/211331356-32ebc501-06c3-4bb4-8359-e754079093b5.png">

### Acceptance criteria

- [ ] Demo of the above components shared with Design team for review (Jeannie, Olivia, Rich)
- [ ] List of any conflicts identified (ie Lead space might not work with left nav)
- [ ] Follow on issues created if needed

**Comment by ariellalgilmore** [comment]
with left nav: https://githubfc7fbvsmftsd-4f0k--9000.local-credentialless.webcontainer.io/
code: https://stackblitz.com/edit/github-fc7fbv-smftsd?file=index.html,src%2Findex.js

without left nav: https://githubfc7fbv2dwjqv-jeaf--9000.local-credentialless.webcontainer.io/
code: https://stackblitz.com/edit/github-fc7fbv-2dwjqv?file=index.html,src%2Findex.js

**Comment by ariellalgilmore** [comment]
<img width="1440" alt="Screen Shot 2023-01-31 at 8 14 23 AM" src="https://user-images.githubusercontent.com/20210594/215799982-e4124dc7-cdec-4884-893a-b3a8271cfde7.png">
<img width="1440" alt="Screen Shot 2023-01-31 at 8 15 44 AM" src="https://user-images.githubusercontent.com/20210594/215800002-01dcd8d5-ed7f-4ce7-a62a-aa351c9e9128.png">

**Comment by oliviaflory** [comment]
Thank you @ariellalgilmore!!

Here are some notes for the future:
- Leadspace doesn’t work (and i tried to highlight in one of the photos) is because we set styles within the Dotcom library to try to center it
   - Would potentially need changes to allow lead space to align in a desired way
- UI shell header extends beyond max breakpoint
   -  Dotcom components (like lead space) are set up to stop any further extension.
- Left navigation covers lead space and footer
   - Potentially could stop Left nav at footer, would need to review alignments
   - All dotcom components (Content block, group, etc) would need a similar grid structure to existing page templates (ie skip the first 4 columns)
